config/routes.rb
Rails.application.routes.draw do
  resources :roomimages
  resources :rs
  get 'reservation/index'
  resources :comments
  devise_for :users, :controllers => {
    :confirmations => 'users/confirmations',
    :registrations => 'users/registrations',
    :sessions => 'users/sessions',
    :passwords => 'users/passwords'
   }

  get 'users/index',to: 'users#index'
  get 'rooms/index',to: 'rooms#index'
  get 'reservation',to: 'reservation#index'
  resources :users
  resources :rooms
  resources :reservation
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
end

app/models/reservation.rb
class Reservation < ApplicationRecord
end

app/models/room.rb
class Room < ApplicationRecord
  validates :name_facility, presence: true
  validates :introduction, presence: true
  validates :price,  presence: true
  validates :address, presence: true
  
  mount_uploader :avatar, AvatarUploader
end

app/models/roomimage.rb
class Roomimage < ApplicationRecord
  mount_uploader :avatar_path, AvatarUploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    @comment = Comment.new
  end

  def create
    @comment = Comment.create params.require(:comment).permit(:content, :image) # POINT
    redirect_to @comment
  end

  def show
    @comment = Comment.find(params[:id])
  end

  def edit
    @comment = Comment.find(params[:id]) 
  end

  def update
    @comment = Comment.find(params[:id])
    @comment.update params.require(:comment).permit(:content, :image) # POINT
    redirect_to @comment
  end
end

app/controllers/reservation_controller.rb
class ReservationController < ApplicationController
  def index
    @reservations = Reservation.all
  end

  def new
    @reservation = Reservation.new
  end

  def create
  end

  def show
  end

  def edit
  end

  def update
  end

  def destroy
  end
end

app/controllers/roomimages_controller.rb
class RoomimagesController < ApplicationController
  before_action :set_roomimage, only: %i[ show edit update destroy ]

  # GET /roomimages or /roomimages.json
  def index
    @roomimages = Roomimage.all
  end

  # GET /roomimages/1 or /roomimages/1.json
  def show
  end

  # GET /roomimages/new
  def new
    @roomimage = Roomimage.new
  end

  # GET /roomimages/1/edit
  def edit
  end

  # POST /roomimages or /roomimages.json
  def create
    @roomimage = Roomimage.new(roomimage_params)

    respond_to do |format|
      if @roomimage.save
        format.html { redirect_to roomimage_url(@roomimage), notice: "Roomimage was successfully created." }
        format.json { render :show, status: :created, location: @roomimage }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @roomimage.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /roomimages/1 or /roomimages/1.json
  def update
    respond_to do |format|
      if @roomimage.update(roomimage_params)
        format.html { redirect_to roomimage_url(@roomimage), notice: "Roomimage was successfully updated." }
        format.json { render :show, status: :ok, location: @roomimage }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @roomimage.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /roomimages/1 or /roomimages/1.json
  def destroy
    @roomimage.destroy

    respond_to do |format|
      format.html { redirect_to roomimages_url, notice: "Roomimage was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_roomimage
      @roomimage = Roomimage.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def roomimage_params
      params.require(:roomimage).permit(:name, :avatar_path)
    end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  def index
    @rooms = Room.all
  end

  def new
    @room = Room.new
  end

  def create 
    @room = Room.new (room_params)
    if @room.save
      redirect_to :rooms
    else
      render "new"
    end
  end

  def show
    @room = Room.find (params[:id])
  end
  
  private
  def room_params
    params.require(:room).permit(:name_facility, :introduction, :price, :address, :avatar, :avatar_cache)
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  def new
    super
  end
  # POST /resource/confirmation
  def create
    super
  end
  # GET /resource/confirmation?confirmation_token=abcdef
  def show
    super
  end

  protected

  def after_resending_confirmation_instructions_path_for(resource_name)
    super(resource_name)
  end
  # The path used after confirmation.
  def after_confirmation_path_for(resource_name, resource)
    super(resource_name, resource)
  end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  def new
    super
  end
  # POST /resource/password
  def create
    super
  end
  # GET /resource/password/edit?reset_password_token=abcdef
  def edit
    super
  end
# PUT /resource/password
  def update
    super
  end

  protected

  def after_resetting_password_path_for(resource)
    super(resource)
  end
  # The path used after sending reset password instructions
  def after_sending_reset_password_instructions_path_for(resource_name)
    super(resource_name)
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true
class Users::SessionsController < Devise::SessionsController
  before_action :configure_sign_in_params, only: [:create]
  # GET /resource/sign_in
  def new
    super
  end
  # POST /resource/sign_in
  def create
    super
  end
  # DELETE /resource/sign_out
  def destroy
    super
  end
  
  protected
  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_in_params
    devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  def new
    super
  end
# POST /resource/unlock
  def create
    super
  end
  # GET /resource/unlock?unlock_token=abcdef
  def show
    super
  end

  protected
  # The path used after sending unlock password instructions
  def after_sending_unlock_instructions_path_for(resource)
    super(resource)
  end
  # The path used after unlocking the resource
  def after_unlock_path_for(resource)
    super(resource)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    
  end

  def new
  end

  def create
  end

  def show
  end

  def edit
  end

  def update
  end

  def destroy
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/reservation_helper.rb
module ReservationHelper
end

app/helpers/roomimages_helper.rb
module RoomimagesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/rs_helper.rb
module RsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/reservation/index.html.erb
<h3>予約済み一覧</h3>

<table>
  <thead>
    <tr>
      <th>画像</th>
      <th>施設名</th>
      <th>紹介文</th>
      <th>合計料金</th>
      <th>チェックイン</th>
      <th>チェックアウト</th>
      <th>予定確定日時</th>
    </tr>
  </thead>

  <tbody>
    <% @rooms.each do |room| %>
    <% @reservation.each do |reservation| %>
      <tr>
        <td></td>
        <td><%= room.name_facility %></td> <!--予約と施設をちゃんとルーティング繋げてないからメソッドエラーになるのか？-->
        <td><%= room.introduction %></td>
        <td><%= room.price %></td>
        <td><%= reservation.checkin %></td>
        <td><%= reservation.checkout %></td>
        <td><%= user.created_at %></td>
      </tr>
    <% end %>
    <% end %>
  </tbody>
</table>

app/views/roomimages/_form.html.erb
<%= form_with(model: roomimage) do |form| %>
  <% if roomimage.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(roomimage.errors.count, "error") %> prohibited this roomimage from being saved:</h2>

      <ul>
        <% roomimage.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :avatar_path %>
    <%= form.text_field :avatar_path %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/roomimages/edit.html.erb
<h1>Editing Roomimage</h1>

<%= render 'form', roomimage: @roomimage %>

<%= link_to 'Show', @roomimage %> |
<%= link_to 'Back', roomimages_path %>

app/views/roomimages/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Roomimages</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Avatar path</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @roomimages.each do |roomimage| %>
      <tr>
        <td><%= roomimage.name %></td>
        <td><%= roomimage.avatar_path %></td>
        <td><%= link_to 'Show', roomimage %></td>
        <td><%= link_to 'Edit', edit_roomimage_path(roomimage) %></td>
        <td><%= link_to 'Destroy', roomimage, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Roomimage', new_roomimage_path %>

app/views/roomimages/new.html.erb
<h1>New Roomimage</h1>

<%= render 'form', roomimage: @roomimage %>

<%= link_to 'Back', roomimages_path %>

app/views/roomimages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @roomimage.name %>
</p>

<p>
  <strong>Avatar path:</strong>
  <%= @roomimage.avatar_path %>
</p>

<%= link_to 'Edit', edit_roomimage_path(@roomimage) %> |
<%= link_to 'Back', roomimages_path %>

app/views/rooms/index.html.erb
<h3>登録済み一覧</h3>

<table>
  <thead>
    <tr>
      <th>画像</th>
      <th>施設名</th>
      <th>紹介文</th>
      <th>料金</th>
      <th>作成日</th>
    </tr>
  </thead>

  <tbody>
    <% @rooms.each do |room| %>
      <tr>
      <% if @room.avatar? %>
        <td><%= image_tag @room.avatar.url %></td>
      <% end %>
        <td><%= room.name_facility %></td>
        <td><%= room.introduction %></td>
        <td>￥<%= room.price %>〜</td>
        <td><%= room.created_at.to_s(:datetime_jp) %></td>
        <td><%= link_to "参照", room %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<p><%= link_to "施設の新規登録", :new_room %></p>

app/views/rooms/new.html.erb
<h3>施設新規登録</h3>

<%= form_with model: @room do |f| %>
  <table>
    <tr>
      <th><%= f.label :name_facility ,"施設名" %></th>
      <td><%= f.text_field :name_facility %></td>
    </tr>

    <tr>
      <th><%= f.label :introduction ,"施設詳細" %></th>
      <td><%= f.text_area :introduction %></td>
    </tr>

    <tr>
      <th><%= f.label :price ,"料金" %></th>
      <td><%= f.text_field :price %></td>
    </tr>

    <tr>
      <th><%= f.label :address ,"住所" %></th>
      <td><%= f.text_field :address %></td>
    </tr>

    <tr>
      <th><%= f.label :avatar , "施設画像" %></th>
      <td><%= f.file_field :avatar %>
      <%= f.hidden_field :avatar_cache %></td>
  </table>

  <div>
    <ul> 
      <li><%= f.submit "登録完了する"%></li>
      <li><%= link_to "情報一覧に戻る", :rooms %></li>
    </ul>
  </div>
<% end %>

app/views/rooms/show.html.erb
<h3>施設詳細</h3>

  <table>
    <tr>
      <th>施設名</th>
      <td><%= @room.name_facility %></td>
    </tr>

    <tr>
      <th>施設詳細</th>
      <td><%= @room.introduction %></td>
    </tr>

    <tr>
      <th>料金</th>
      <td><%= @room.price %></td>
    </tr>

    <tr>
      <th>施設画像</th>
      </td>

      <ul>
        <li><%= link_to "戻る", :back %></li>
      </ul>
  </table>